# Generated by Django 6.0 on 2025-12-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('posts', '0003_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default='Sin Categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
